name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug"]
body:
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: "Windows 11, macOS Ventura, Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How can we reproduce this issue?
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
